export const ADD_PRODUCT_REQUEST = "ADD_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_RESET = "ADD_PRODUCT_RESET";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";


